apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
    # This label allows RHDH to find the Service
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  selector:
    app: ${{ values.name }}
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
